entrada = int(input())
if entrada == 1: print("January")
if entrada == 2: print("February")
if entrada == 3: print("March")  
if entrada == 4: print("April")  
if entrada == 5: print("May")  
if entrada == 6: print("June")  
if entrada == 7: print("July")  
if entrada == 8: print("August")  
if entrada == 9: print("September")  
if entrada == 10: print("October")  
if entrada == 11: print("November")  
if entrada == 12: print("December")  
