entrada = input()
dados = entrada.split()
x = float(dados[0])
y = float(dados[1])

if x == 0 and y > 0 or x == 0 and y < 0: print("Eixo y")
if x > 0 and y == 0 or x < 0 and y == 0: print("Eixo x")
if x > 0 and y > 0: print("Q1")
if x < 0 and y > 0: print("Q2")
if x < 0 and y < 0: print("Q3")
if x > 0 and y < 0: print("Q4")
if x == 0.0 and y == 0.0 or x == 0 and y == 0: print("Origem")